apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: microservices
spec:
  tls:
  - hosts:
    - {{HOSTNAME}}
    secretName: tls-certs
  rules:
  - host: {{HOSTNAME}}
    http:
      paths:
      - path: /books
        pathType: Prefix
        backend:
          service:
            name: book-service
            port: 
              number: 8001
  - host: {{HOSTNAME}}
    http:
      paths:
        - path: /authors
          pathType: Prefix
          backend:
            service:
              name: author-service
              port:
                number: 8001
  - host: {{HOSTNAME}}
    http:
      paths:
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port: 
              number: 8001